### ISSUE TITLE
Mention in docs about Azure limits and quotas

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/m-azure-kubernetes-service#13]
**Is your feature request related to a problem? Please describe.**
When using the module, for some regions there is an error related to resource unavailability in the region. We need a mention in documentation about supported regions.

**Describe the solution you'd like**
Extend documentation.

**Describe alternatives you've considered**
n/a

**Additional context**

Error:
```text
Error: Error creating Resource Group "mop-module-tests-rg": resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LocationNotAvailableForResourceGroup" Message="The provided location 'switzerlandwest' is not available for resource group. List of available regions is 'centralus,eastasia,southeastasia,eastus,eastus2,westus,westus2,northcentralus,southcentralus,westcentralus,northeurope,westeurope,japaneast,japanwest,brazilsouth,australiasoutheast,australiaeast,westindia,southindia,centralindia,canadacentral,canadaeast,uksouth,ukwest,koreacentral,koreasouth,francecentral,southafricanorth,uaenorth,australiacentral,switzerlandnorth,germanywestcentral,norwayeast'."
```

On the Azure web interface: Home / Subscriptions / <NAME> then pick "Usage + quotas". You can find info about quotas for each region.

**Comment by rafzei** [comment]
@sk4zuzu The link (a reference to comment in another issue) in description is broken, could you fix it?
Currently, we don't have any documentation beside readme.md so two options here: 
- start documentation of module
- add above info to readme.md

I would prefer the first option :+1:

**Comment by rpudlowski93** [comment]
Additionally, please add additional column with "steps" since some parameters in some steps are different. Doc document: https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/develop/docs/INPUTS.adoc

It is already done in the following file and repo: https://github.com/epiphany-platform/m-aws-kubernetes-service/blob/develop/docs/INPUTS.adoc. Its is very small and quick change and we don't want to do new task for it.

**Comment by mkyc** [comment]
> Additionally, please add additional column with "steps" since some parameters in some steps are different. Doc document: https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/develop/docs/INPUTS.adoc

Will be updated in #38

**Comment by mkyc** [comment]
Should be checked together with #29

**Comment by przemyslavic** [comment]
Information about Azure subscription and service limits, quotas, and constraints has been added to the `README` file.
