### ISSUE TITLE
Add tests for AKS in existing subnet

### ISSUE THREAD

**Issue by rpudlowski93** [epiphany-platform/m-azure-kubernetes-service#29]
**Is your feature request related to a problem?** 
In the task #7 we added ability to create AKS in already existing subnet. We need to add new test for this feature in order to check if everything deploy properly for this scenario. Right now, we only test example of AzKS module deployed in AzBI.

**Describe the solution you'd like**
I would like to create test that check AzKS in existing subnet. During the test we should create resource group, vnet and subnet and deploy there an example of AzKS. 

We already have tests implemented in this repository but before doing this task, we should to rewrite the tests into GO language and only then do this task.

**Describe alternatives you've considered** 

**Additional context**

**Comment by mkyc** [comment]
So this task will actually contain 2 steps: 
 * rewrite existing tests into Golang
 * add tests for AKS in existing subnet

And then 3rd step (possibly to be excluded to separate task: 
 * rewrite module logic into Golang

This last step is actually required because of bigger changes introduced in Azure related modules.

**Comment by mkyc** [comment]
In the PR #38 there are following changes introduced: 
 * whole module logic rewritten into Golang
 * module structures using e-structs package
 * whole integration tests rewritten into Golang
 * removed optional RG, VNET and Subnet creation from module. It has to be always provided from outside. 
 * documentation heavily improved
 * more test cases introduced especially for init phase
 * pipelines unified

... and number of smaller improvements.

**Comment by przemyslavic** [comment]
Tested `make build`, `make test` and `make pipeline-test`.
Executed the following commands: `init`, `plan`, `apply`, `plan --destroy`, `destroy` withe different parameters (`--debug=true`, `--omit_state`, ... )
I was able to install the `aks` cluster on top of the `azbi` module.

Several tasks have been created for some issues:
https://github.com/epiphany-platform/m-azure-kubernetes-service/issues/44
https://github.com/epiphany-platform/m-azure-kubernetes-service/issues/45
https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/75
