### ISSUE TITLE
[BUG] Unable to deploy AKS cluster due to changed versions

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/m-azure-kubernetes-service#3]
Today I faced this issue running the basic_flow example:
```
Error: creating Managed Kubernetes Cluster "mop-module-tests-aks" (Resource Group "mop-module-tests-rg"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="AgentPoolK8sVersionNotSupported" Message="Version 1.17.7 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list"
```

**Comment by mkyc** [comment]
Nice one. Using [this page](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions) I checked supported versions:

```
az aks get-versions --location germanywestcentral --output table
KubernetesVersion    Upgrades
-------------------  ------------------------
1.19.0(preview)      None available
1.18.8               1.19.0(preview)
1.18.6               1.18.8, 1.19.0(preview)
1.17.11              1.18.6, 1.18.8
1.17.9               1.17.11, 1.18.6, 1.18.8
1.16.15              1.17.9, 1.17.11
1.16.13              1.16.15, 1.17.9, 1.17.11
```

and in defaults we have: 

```
variable "kubernetes_version" {
  description = "Kubernetes version"
  type        = string
  default     = "1.17.7"
}
```

It must have changed today, as I was doing tests yesterday with default values. For now we should probably update defaults to newest ones.

**Comment by sk4zuzu** [comment]
I bumped the version to 1.18.6 https://github.com/epiphany-platform/m-azure-kubernetes-service/pull/4 and fixed nasty issue with old url of the docker images.

**Comment by atsikham** [comment]
Can be tested together with this task - https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/1624

**Comment by atsikham** [comment]
Verified together with another [issue](https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/1624). Correct k8s version 1.18.6 installed.
