### ISSUE TITLE
Unify docker image name across module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-kubernetes-service#36]
**Is your feature request related to a problem? Please describe.**
Currently we have multiple places with image name and tag. We should unify it to have one single place to update it.

**Describe the solution you'd like**
Check integration tests. There is an image name and tag specified and it may be the cause to run tests not with the latest changes. Suggestion here is to set tag as a variable and pass to tests execution. Check AWS module tests and pipeline to see how it's done there.
If there is something to update in documentation about tests execution, it should be updated.

**Describe alternatives you've considered**
No.

**Additional context**

Mirror of task [38 from another module](https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/38). And [here](https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/55) is related PR.

**Comment by mkyc** [comment]
This one would be solved in #38.

**Comment by mkyc** [comment]
Should be checked together with #29

**Comment by przemyslavic** [comment]
@mkyc there is an error that occurs while running the task `Cleanup Local Image` in the pipeline.
The reason is that the variable `registry_name` is not set as it has been renamed to `registryName`.

Moving this task back to TODO.

**Comment by przemyslavic** [comment]
Fixed
