### ISSUE TITLE
Remove dashboard from AKS due to its deprecation

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-kubernetes-service#39]
As of 1.18 dashboard is already deprecated, and in 1.19 it will cause error in terraform with this section: 

```
addon_profile {
    kube_dashboard {
      enabled = var.kube_dashboard_enabled
    }
  }
```

https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard

**Comment by mkyc** [comment]
@rpudlowski93 can you have look at this issue if I get it correctly? As far as I understand we have two options: 
 - remove dashboard definition completely from terraform 
 - make it conditional on k8s version used in AKS

I personally would rather remove it completely due to it's deprecation and make default version > 1.19.

**Comment by rpudlowski93** [comment]
Yes, exactly. I would also remove the dashboard completely, it is deprecated and I already heard that one team use another "better" tool fo the UI

**Comment by przemyslavic** [comment]
The dashboard has been removed.
The `save` and `load` methods are now called from the `e-structures` module.
