### ISSUE TITLE
Introduce log level flag instead of debug parameter

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/m-azure-kubernetes-service#44]
It would be nice to be able to control the log level like we have in the `azbi` module. So instead of the `debug` parameter, which by default is false, what makes the command output very silent, we could set the log level with the default INFO level.

azbi PR: https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/71/files

**Comment by mkyc** [comment]
It should be something similar to [this PR](https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/71).

**Comment by przemyslavic** [comment]
The following logging levels have been introduced: `Panic`, `fatal`, `error`, `warn`, `info`, `debug` and `trace` with the default `info` level.
Now we can see exactly what is happening while executing specific commands.
