### ISSUE TITLE
[BUG] Cannot reapply the configuration after it has been changed

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/m-azure-kubernetes-service#45]
I am unable to reapply the configuration after making some changes to the `azks-config.json` file.
To reproduce:
1. Execute `init`, `plan` and `apply` commands.
2. Make some changes to `azks-config.json` file.
3. Execute  `plan` command.
4. Execute  `apply` command.

It fails with error:
```
2021-02-24T13:09:47Z FTL go/src/github.com/epiphany-platform/m-azure-kubernetes-service/cmd/apply.go:54 > incorrect state error="unexpected state: applied"
```

**Comment by mkyc** [comment]
It's possible that we should remove following state check in in `apply` command:

```golang
if !reflect.DeepEqual(state.AzKS, &st.AzKSState{}) && state.AzKS.Status != st.Initialized && state.AzKS.Status != st.Destroyed {
	logger.Fatal().Err(errors.New(string("unexpected state: " + state.AzKS.Status))).Msg("incorrect state")
}
```

**Comment by przemyslavic** [comment]
Fixed.
Now the user can edit the `azks-config.json` file to modify the previously applied configuration and rerun the `plan` and `apply` commands to apply the changes.
