### ISSUE TITLE
[BUG] fix incorrect initialisation of "azbi" config in state file in "initialized without any prior steps" test

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-kubernetes-service#47]
**Describe the bug**

If you run tests with new e-structures library but without changes in azks code tests will fail on state validation. 

Possibly there is just one test ("initialized without any prior steps") incorrect with incorrect provided state file, but it has to be investigated more carefully. 

**How to reproduce**

1. locally build azks module with new e-structures module but without any changes
2. run integration tests

it should fail. 

**Expected behavior**
Do not fail. 

**Config files**
n/a

**Environment**
n/a

**Additional context**

Workaround is implemented in [e-structures v0.0.7](https://github.com/epiphany-platform/e-structures/releases/tag/v0.0.7) and should be introduced in module with usage of e-structures "load" and "save" packages like [here](https://github.com/epiphany-platform/m-host-init/pull/1/files#diff-58ff10aae5b8f8645717df56684a06f13edcd0f0cc7f7d44560a6066c3739209R54)

**Comment by mkyc** [comment]
Should be checked together with #39

**Comment by przemyslavic** [comment]
Test fixed in #39 [PR #46].
