### ISSUE TITLE
Add more parameter in order to create customizable, private AKS cluster

### ISSUE THREAD

**Issue by pprach** [epiphany-platform/m-azure-kubernetes-service#8]
Add more parameter to create private cluster

**Is your feature request related to a problem?** 
Right now, we can customize only a few parameters in our AKS module: 

```
M_NAME ?= epiphany
M_RG_NAME ?= $(M_NAME)-rg
M_VNET_NAME ?= $(M_NAME)-vnet
M_ADDRESS_PREFIX ?= 10.0.0.0/16

# default node pool
M_SIZE ?= 2
M_MIN ?= 2
M_MAX ?= 5
M_VM_SIZE ?= Standard_DS2_v2
M_DISK_SIZE ?= 36
M_AUTO_SCALING ?= true
M_VMS_RSA ?= vms_rsa
```

**Describe the solution you'd like**
We would like to create fully customizable private cluster, with all useful options which can be needed such as: 
```
- K8S_VERSION
- PUBLIC_IP_ENABLED
- NETWORK_PLUGIN
- NETWORK_POLICY
- AUTO_SCALER_PROFILE 
- OS_TYPE
- RBAC_ENABLED
- NODE_TYPE
etc..
```

**Describe alternatives you've considered**

**Additional context**
Here we have example how the fully customizable pivate cluster should look like: [link](https://github.com/epiphany-platform/build-system/tree/develop/technical/sources/terraform/modules/aks)

**Comment by atsikham** [comment]
Please test and close #9 together with this task.

**Comment by rpudlowski93** [comment]
Tested with AzKS module v.0.0.2. Works as expected, cluster with changed additional arguments created and works fine.
