### ISSUE TITLE
Move terraform code from module directly to "top level" code

### ISSUE THREAD

**Issue by pprach** [epiphany-platform/m-azure-kubernetes-service#9]
Move terraform code from module directly to "top level" code

**Describe the bug**
In these two locations files are duplicated: 
- resources/terraform/modules/aks/
- resources/terraform/

**To Reproduce**

**Config files**

**Expected behavior**
There should be no duplicates

**OS (please complete the following information):**

**Cloud Environment (please complete the following information):**

**Additional context**

Check the differences in the first place (filenames are the same but might differ with the content a bit) and clean it up. 
Desired location is just resources/terraform/

**Comment by ar3ndt** [comment]
@pprach what do you mean by "top level" code?

**Comment by pprach** [comment]
aks terraform code is sitting in directory terraform/module/aks when in my opinion it should be on top level in terraform.

**Comment by ar3ndt** [comment]
There is a data already on "top level". This task needs checking the differences in the first place and cleaning it up.

**Comment by pprach** [comment]
This is not on the top level because top level is in directory terraform. The code which creating aks is in terraform/modules/aks so this is not top dir.

**Comment by DaOsie** [comment]
Having AKS extracted to module feels unnecessary for me since there are not much resources defined there, however moving that code is just cosmetic change. Data source for resource group is indeed duplicated inside the module.

**Comment by rpudlowski93** [comment]
Change done in mentioned PR. Cluster created properly with these changes. Module moved to the "top level".
